
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

 run-selected-unittests:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
            
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.0
        id: setup_msbuild
              
      - name: Run MSBuild
        id: run_msbuild
        run: |
          msbuild .\CalculatorLibrary.sln  /t:clean /p:Configuration=Debug
          nuget restore .\CalculatorLibrary.sln
          msbuild .\CalculatorLibrary.sln  /t:build /p:Configuration=Debug
     
      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest

      - name: Test Add
        id: run_vstest
        working-directory: CalcLibTest\bin\Debug\net8.0
        run: vstest.console.exe CalcLibTest.dll /Tests:TestMethod1
